---
- name: 'Dock tilesize'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'tilesize'
    type: 'float'
    value: 60
    state: 'present'
  notify: 'restart dock'

- name: 'Dock autohide'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'autohide'
    type: 'bool'
    value: 'TRUE'
    state: 'present'
  notify: 'restart dock'
